spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/notifications
    username: un
    password: pw
  application.name: notification-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    exchange:
      name: survey-exchange
    queue:
      name: survey-queue
    routing:
      key: survey.#

bot:
  name: my_pp0_bot
  token: 7055232680:AAFlndKXM02Pe_Dx3XUyE6tom3a0WtGHUlE

server:
  port: 8084