spring:
  application.name: user-service
  ldap:
    embedded:
      ldif: classpath:schema.ldif
      port: 8389
      base-dn: dc=springframework,dc=org

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/userdb
    username: un
    password: pw

  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: un
    password: pw

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org.springframework.ldap: DEBUG
    org.springframework.security: DEBUG
