spring:
  application.name: user-service
  ldap.embedded:
    ldif: classpath:schema.ldif
    base-dn: dc=springframework,dc=org
    port: 8389

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/userdb
    username: un
    password: pw

  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: un
    password: pw

  flyway:
    enabled: true
    locations: classpath:db/migration
