version: '3'
services:
  payment_db:
    image: container-registry.oracle.com/database/enterprise
    restart: always
    environment:
      ORACLE_SID: payments
      ORACLE_PDB: pdb1
      ORACLE_PWD: pw
    volumes:
      - payment_db_data:/opt/oracle/oradata
    ports:
      - "1521:1521"

  survey_db:
    image: mongo:7.0.9
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - survey_db_data:/data/db

  notifications-db:
    image: postgres:16.1
    container_name: notifications_db
    environment:
      POSTGRES_DB: notifications
      POSTGRES_USER: un
      POSTGRES_PASSWORD: pw
    ports:
      - "5432:5432"
    volumes:
      - ./notifications:/docker-entrypoint-initdb.d
      - notifications_db_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  payment_db_data:
  survey_db_data:
  notifications_db_data:
