version: '3'
services:
  payment_db:
    image: container-registry.oracle.com/database/enterprise
    restart: always
    environment:
      ORACLE_SID: payments
      ORACLE_PDB: pdb1
      ORACLE_PWD: pw
    volumes:
      - payment_db_data:/opt/oracle/oradata
    ports:
      - "1521:1521"

  survey_db:
    image: mongo:7.0.9
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: un
      MONGO_INITDB_ROOT_PASSWORD: pw
    volumes:
      - survey_db_data:/data/db
    ports:
      - "27017:27017"

  user-db:
    image: postgres:16.1
    container_name: user_db
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: un
      POSTGRES_PASSWORD: pw
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ldap:
    image: osixia/openldap:1.5.0
    container_name: ldap
    environment:
      LDAP_ORGANISATION: "springframework"
      LDAP_DOMAIN: "springframework.org"
      LDAP_ADMIN_PASSWORD: "secret"
    ports:
      - "8389:389"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
    command: "--copy-service"

volumes:
  payment_db_data:
  survey_db_data:
  postgres_data:
  ldap_data:
  ldap_config:
